# AZURE_OPENAI_API_KEY : '' 
# AZURE_OPENAI_ENDPOINT : ''
# AZURE_OPENAI_VERSION : '2024-08-01-preview' 
# AZURE_GPT4O_MODEL : 'gpt-4o'
# AZURE_OPENAI_EMBEDDINGS_MODEL: ''
# LANGCHAIN_ENDPOINT : 'https://api.smith.langchain.com'
# LANGCHAIN_API_KEY : ''
# LANGCHAIN_PROJECT : ''
# TAVILY_API_KEY : 'tvly-'
# AI_SEARCH_KEY: ''
# AI_SEARCH_ENDPOINT: ''




# GOOGLE_API_KEY: 'AIzaSyAE94X6l_wfkVBXOdAIi5SZBfHswxjUFJM'
# GOOGLE_API_KEY: 'AIzaSyC5giosW9nbcgqpzepnvjdsmW8hrmkEeB4'
GOOGLE_API_KEY: 'AIzaSyCP99HXunPMPTWkitdFEzGBFgAXp62mYbg'
GEMINI_MODEL: 'gemini-2.0-flash-lite' 
LANGSMITH_TRACING : 'true'
LANGCHAIN_ENDPOINT: 'https://api.smith.langchain.com'
LANGCHAIN_API_KEY: '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'
LANGCHAIN_PROJECT: ''
AI_SEARCH_KEY: ''
AI_SEARCH_ENDPOINT: ''
AI_SEARCH_INDEX: 'your-search-index'
AI_SEARCH_VECTOR_SIZE: 1536
AI_SEARCH_K: 3
AI_SEARCH_SCORE_THRESHOLD: 0.5
AI_SEARCH_TOP_K: 3
AI_SEARCH_TOP_P: 0.7
AI_SEARCH_MAX_TOKENS: 1000
AI_SEARCH_TEMPERATURE: 0.7
AI_SEARCH_FREQUENCY_PENALTY: 0.0
AI_SEARCH_PRESENCE_PENALTY: 0.0
AI_SEARCH_STOP: []
AI_SEARCH_STREAM: true
AI_SEARCH_VERBOSE: false
AI_SEARCH_ENGINE: 'text-davinci-003'
AI_SEARCH_PROMPT: ''
AI_SEARCH_PROMPT_TEMPLATE: ''
AI_SEARCH_PROMPT_PREFIX: ''
AI_SEARCH_PROMPT_SUFFIX: ''
AI_SEARCH_PROMPT_INPUT_VARIABLES: []
AI_SEARCH_PROMPT_OUTPUT_PARSER: ''
AI_SEARCH_PROMPT_MEMORY: ''
AI_SEARCH_PROMPT_CHAT_HISTORY: ''
AI_SEARCH_PROMPT_CHAT_MESSAGE_HISTORY: ''
AI_SEARCH_PROMPT_CHAT_MESSAGE_HISTORY_INPUT_KEY: ''
AI_SEARCH_PROMPT_CHAT_MESSAGE_HISTORY_OUTPUT_KEY: ''
AI_SEARCH_PROMPT_CHAT_MESSAGE_HISTORY_OUTPUT_PARSER: ''